import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "../auth";
import NextAuthProvider from "./common/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <NextAuthProvider session={session}>
      <html lang="en">
        <body className="main-font">{children}</body>
      </html>
    </NextAuthProvider>
  );
}
